import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToastProvider from "../components/ui/ToastProvider";
import { AuthProvider } from "../context/AuthContext";
import { CartProvider } from "../context/CartContext";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
		>
			<body className="min-h-full flex flex-col bg-orange-50">
				{/* <Header /> */}
					<AuthProvider>
						<CartProvider>
							<main className="min-h-[calc(100vh-82px)]">
								{children}
								<ToastProvider />
							</main>
						</CartProvider>
					</AuthProvider>
				{/* <Footer /> */}
			</body>
		</html>
	);
}
